name: proto_study_point
description: Prototype for study point
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  enum_to_string: ^1.0.14
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  font_awesome_flutter: ^8.10.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  shortuuid: ^2.1.1
  url_launcher: ^5.7.10
  youtube_player_flutter: ^6.1.1

dev_dependencies: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
